management.endpoints.web.exposure.include: "*"
server:
  port: 6003
spring:
  application:
    name: account-jdbc-caching-rest-service
  liquibase:
    enabled: true
    # Required running: CREATE SCHEMA IF NOT EXISTS retail;
    defaultSchema: "gf_cache"
    change-log: "classpath:db/changelog/postgres/changelog-v1.sql"
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  data:
    gemfire:
      pool.default.locators: localhost[10334]
