spring:
  application:
    name: gemfire-vectordb-perftest
  ai:
    vectorstore:
      gemfire:
        host: localhost
        port: 7080
        initialize-schema: true
    ollama:
      init:
        pull-model-strategy: always
        embedding:
          additional-models:
            - mxbai-embed-large
            - nomic-embed-text
server:
  port: 0