server:
  port: 8088
spring:
  application:
    name:  vector-web-app
  ai:
    vectorstore:
      gemfire:
        host: localhost
        port: 7080
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
#          model: llama3
          model: llama3.1:8b
#      model: wizardlm2:7b
      init:
        pull-model-strategy: WHEN_MISSING
    mcp:
      client:
#        enabled: true
        name: ${spring.application.name}
        version: 1.0.0
#        toolcallback:
#          enabled: true
        type: SYNC
#        sse:
#          connections:
#            server1:
#              url: http://localhost:9088
#              sse-endpoint: /custom-sse
#              env:
#                API_KEY: your-api-key
#                DEBUG: "true"